# Generated by Django 4.0.4 on 2022-04-13 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('profession', models.IntegerField()),
                ('freelancer', models.IntegerField()),
                ('language', models.IntegerField()),
                ('description', models.TextField(max_length=1000)),
            ],
        ),
    ]
