# Generated by Django 3.2.14 on 2022-07-11 16:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.IntegerField()),
                ('title', models.CharField(max_length=70)),
                ('contact', models.CharField(max_length=17)),
                ('price', models.FloatField(blank=True)),
                ('address', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='service/%Y/%m/%d/')),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_job', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('profession', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=17)),
                ('salary', models.FloatField(blank=True, validators=[django.core.validators.MaxValueValidator(99.99)])),
                ('language_french', models.BooleanField(blank=True)),
                ('language_english', models.BooleanField(blank=True)),
                ('language_dutch', models.BooleanField(blank=True)),
                ('drivers_license', models.BooleanField(blank=True)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
