# Generated by Django 4.0.4 on 2022-05-04 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_job', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('profession', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=20)),
                ('salary', models.IntegerField(blank=True)),
                ('language_french', models.BooleanField(blank=True)),
                ('language_english', models.BooleanField(blank=True)),
                ('language_dutch', models.BooleanField(blank=True)),
                ('drivers_license', models.BooleanField(blank=True)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
