# Generated by Django 4.0.4 on 2022-04-13 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workmodel',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
