# Generated by Django 3.2.5 on 2022-05-01 14:22

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workmodel',
            name='contact',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='workmodel',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
