# Generated by Django 4.0.4 on 2022-05-01 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_auto_20220501_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workmodel',
            name='contact',
            field=models.CharField(max_length=20),
        ),
    ]
