# Generated by Django 4.0.4 on 2022-04-18 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_alter_workmodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workmodel',
            name='freelancer',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='workmodel',
            name='language',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='workmodel',
            name='profession',
            field=models.CharField(max_length=50),
        ),
    ]
