# Generated by Django 4.0.4 on 2022-05-07 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_alter_workmodel_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workmodel',
            name='salary',
            field=models.FloatField(blank=True, max_length=4),
        ),
    ]
