# Generated by Django 4.0.4 on 2022-05-03 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_alter_workmodel_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='workmodel',
            name='type_job',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
