# Generated by Django 3.2.13 on 2022-06-14 18:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_alter_workmodel_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_service', models.IntegerField()),
                ('title', models.CharField(max_length=70)),
                ('contact', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,15}$')])),
                ('price', models.FloatField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='service/%Y/%m/%d/')),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='workmodel',
            name='contact',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='workmodel',
            name='salary',
            field=models.FloatField(blank=True, validators=[django.core.validators.MaxValueValidator(99.99)]),
        ),
    ]
